version: '3.7'

services:
  app:
    container_name: app-quarkus
    image: "tcelor/security-project:1.0.0-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: "vertx-reactive:postgresql://postgres:5432/elytron_security_jpa"
    depends_on:
      - postgres
  postgres:
    container_name: db
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "quarkus"
      POSTGRES_PASSWORD: "quarkus"
      POSTGRES_DB: "elytron_security_jpa"
    ports:
      - "5431:5432"